#pragma once
#include <stdint.h>

typedef enum {
	SVC_MAIN_PROC_EVENT_TICK           = 1<<0,
	SVC_MAIN_PROC_EVENT_KEY_UP         = 1<<1,
	SVC_MAIN_PROC_EVENT_KEY_DOWN       = 1<<2,
	SVC_MAIN_PROC_EVENT_KEY_ENTER      = 1<<3,
	SVC_MAIN_PROC_EVENT_KEY_UP_LONG    = 1<<4,
	SVC_MAIN_PROC_EVENT_KEY_DOWN_LONG  = 1<<5,
	SVC_MAIN_PROC_EVENT_KEY_ENTER_LONG = 1<<6,
	SVC_MAIN_PROC_EVENT_AUX_TIMER      = 1<<7
} svc_main_proc_event_t;

#define SVC_MAIN_PROC_EVENT_KEY_ANY (SVC_MAIN_PROC_EVENT_KEY_UP | SVC_MAIN_PROC_EVENT_KEY_DOWN | SVC_MAIN_PROC_EVENT_KEY_ENTER)
#define SVC_MAIN_PROC_EVENT_KEY_ANY_LONG (SVC_MAIN_PROC_EVENT_KEY_UP_LONG | SVC_MAIN_PROC_EVENT_KEY_DOWN_LONG | SVC_MAIN_PROC_EVENT_KEY_ENTER_LONG)

void svc_main_proc(svc_main_proc_event_t event);
